In [1]:
import numpy as np

## Array Properties

In [3]:
np.random.seed(42)
rng = np.random.default_rng()

In [45]:
sales_matrix = np.array([rng.integers(150, 210, 7),
                        rng.integers(130, 190, 7),
                        rng.integers(120, 180, 7)])

In [46]:
sales_matrix.shape

(3, 7)

In [47]:
sales_matrix.size

21

In [48]:
sales_matrix.dtype

dtype('int64')

In [49]:
# cube - 3D
sales = np.zeros((3, 4, 7)) # 3 stores, 4 weeks, 7 days
sales

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [50]:
sales.shape, sales.size, sales.dtype

((3, 4, 7), 84, dtype('float64'))

## Operations on Numpy Arrays

In [53]:
# sales data
# 7 days in a week
# 5 items
sales_matrix = np.array([
    rng.integers(150, 210, 7),
    rng.integers(130, 190, 7),
    rng.integers(120, 180, 7),
    rng.integers(110, 170, 7),
    rng.integers(100, 160, 7)
])

In [59]:
sales_matrix.ndim

2

In [60]:
sales_matrix.shape, sales_matrix.size, sales_matrix.dtype

((5, 7), 35, dtype('int64'))

In [66]:
# total weekly sales
total_sales = np.sum(sales_matrix, axis=0) # rows
total_sales

array([827, 758, 746, 790, 728, 768, 703], dtype=int64)

In [67]:
# max sales day for item 1
car_sales = sales_matrix[0]

print('Index:')
np.argmax(car_sales)

Index:


1

In [69]:
# average daily sales
print('Avg daily sales: ')
np.mean(sales_matrix, axis=1) # cols

Avg daily sales: 


array([176.85714286, 165.        , 159.42857143, 137.42857143,
       121.28571429])

In [72]:
# days with sales above a threshold
threshold = 150
action_figure_sales = sales_matrix[3]

np.where(action_figure_sales > threshold)

(array([2, 3], dtype=int64),)

In [74]:
action_figure_sales[2], action_figure_sales[3]

(163, 159)

In [76]:
# Rearranging data - sorting
puzzle_sales = sales_matrix[2]

np.sort(puzzle_sales)

array([132, 152, 161, 164, 166, 167, 174], dtype=int64)

In [77]:
# statistical analysis - mean, variance, standard deviation
np.mean(sales_matrix, axis=0)

array([165.4, 151.6, 149.2, 158. , 145.6, 153.6, 140.6])

In [78]:
np.var(sales_matrix, axis=0)

array([ 811.84, 1053.44,  550.56,  912.8 ,  265.84,  163.04,  755.04])

In [79]:
np.std(sales_matrix, axis=0)

array([28.49280611, 32.45674044, 23.464015  , 30.21258016, 16.30460058,
       12.76871176, 27.47799119])

In [82]:
# find position
vehicles = np.array(['car', 'bike', 'plane'])
np.where(vehicles == 'bike')

(array([1], dtype=int64),)

## Accessing Array Elements
Main methods:
1. Indexing
2. Slicing
3. Boolean Indexing
4. Advanced Indexing

## Reshaping Arrays
np.reshape

## Broadcasting