In [1]:
import numpy as np

In [2]:
runs = np.array([54, 78, 23, 89, 101, 56, 45, 67, 90, 33, 23, 76, 85, 95, 41, 65, 75, 80, 45, 29, 34, 78, 92, 101, 50, 60, 71, 66, 85, 47])
balls = np.array([60, 70, 30, 95, 110, 65, 50, 75, 100, 45, 35, 85, 100, 120, 55, 70, 80, 85, 60, 40, 50, 80, 105, 115, 55, 70, 80, 75, 90, 55])

1. What is the total number of runs scored in the series?
2. What is the average number of runs scored per match?
3. What is the average strike rate of the players?
4. What is the shape of the runs array?
5. What is the number of runs scored by the 5th player?
6. What is the total number of runs scored in the last five matches?
7. Total runs scored by players who faced more than 80 balls.
8. Identify the indices where players scored more than 80 runs.
9. Extract the runs for the 1st, 3rd, and 5th players from the runs array.
10. Find the runs scored on the 1st and 2nd matches and 4th and 5th matches.

In [3]:
# 1
np.sum(runs)

1934

In [4]:
# 2
np.mean(runs)

64.46666666666667

In [5]:
# 3
runs / balls * 100

array([ 90.        , 111.42857143,  76.66666667,  93.68421053,
        91.81818182,  86.15384615,  90.        ,  89.33333333,
        90.        ,  73.33333333,  65.71428571,  89.41176471,
        85.        ,  79.16666667,  74.54545455,  92.85714286,
        93.75      ,  94.11764706,  75.        ,  72.5       ,
        68.        ,  97.5       ,  87.61904762,  87.82608696,
        90.90909091,  85.71428571,  88.75      ,  88.        ,
        94.44444444,  85.45454545])

In [7]:
# 4
runs.shape

(30,)

In [8]:
# 5
runs[4]

101

In [9]:
# 6
runs[:5].sum()

345

In [10]:
# 7
np.sum(runs[np.where(balls > 80)])

894

In [11]:
# 8
np.where(runs > 80)

(array([ 3,  4,  8, 12, 13, 22, 23, 28], dtype=int64),)

In [16]:
# 9
runs[[0, 2, 4]]

array([ 54,  23, 101])

In [19]:
# 10
runs[[0, 1, 3, 4]]

array([ 54,  78,  89, 101])